sonar.organization=thadir
sonar.projectKey=Thadir_cussijn-tree-view
sonar.projectName=Cussijn Tree View

sonar.sources=extension
sonar.exclusions=**/*.test.js
sonar.tests=extension
sonar.test.inclusions=**/*.test.js

sonar.sourceEncoding=UTF-8
